version: '3'
services:
  ursho:
    restart: always
    image: ursho
    ports:
      - 8080:8080
    depends_on:
      - app_postgres
  app_postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432