// Code generated by protoc-gen-go. DO NOT EDIT.
// source: url_shortener.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GenerateRequest struct {
	Pcurl                string   `protobuf:"bytes,1,opt,name=pcurl,proto3" json:"pcurl,omitempty"`
	MobileUrl            string   `protobuf:"bytes,2,opt,name=mobileUrl,proto3" json:"mobileUrl,omitempty"`
	MobileClientUrl      string   `protobuf:"bytes,3,opt,name=mobileClientUrl,proto3" json:"mobileClientUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{0}
}
func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (dst *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(dst, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetPcurl() string {
	if m != nil {
		return m.Pcurl
	}
	return ""
}

func (m *GenerateRequest) GetMobileUrl() string {
	if m != nil {
		return m.MobileUrl
	}
	return ""
}

func (m *GenerateRequest) GetMobileClientUrl() string {
	if m != nil {
		return m.MobileClientUrl
	}
	return ""
}

type GenerateReply struct {
	Shortener            string   `protobuf:"bytes,1,opt,name=shortener,proto3" json:"shortener,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=clientType,proto3" json:"clientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateReply) Reset()         { *m = GenerateReply{} }
func (m *GenerateReply) String() string { return proto.CompactTextString(m) }
func (*GenerateReply) ProtoMessage()    {}
func (*GenerateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{1}
}
func (m *GenerateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateReply.Unmarshal(m, b)
}
func (m *GenerateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateReply.Marshal(b, m, deterministic)
}
func (dst *GenerateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateReply.Merge(dst, src)
}
func (m *GenerateReply) XXX_Size() int {
	return xxx_messageInfo_GenerateReply.Size(m)
}
func (m *GenerateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateReply proto.InternalMessageInfo

func (m *GenerateReply) GetShortener() string {
	if m != nil {
		return m.Shortener
	}
	return ""
}

func (m *GenerateReply) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type ShortDetailReply struct {
	// 唯一Id
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// shortener 短链接
	Shortener string `protobuf:"bytes,2,opt,name=shortener,proto3" json:"shortener,omitempty"`
	// clientType 客户端类型
	ClientType string `protobuf:"bytes,3,opt,name=clientType,proto3" json:"clientType,omitempty"`
	// url 原url
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// creatTime 创建时间
	CreateTime           string   `protobuf:"bytes,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortDetailReply) Reset()         { *m = ShortDetailReply{} }
func (m *ShortDetailReply) String() string { return proto.CompactTextString(m) }
func (*ShortDetailReply) ProtoMessage()    {}
func (*ShortDetailReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{2}
}
func (m *ShortDetailReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortDetailReply.Unmarshal(m, b)
}
func (m *ShortDetailReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortDetailReply.Marshal(b, m, deterministic)
}
func (dst *ShortDetailReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortDetailReply.Merge(dst, src)
}
func (m *ShortDetailReply) XXX_Size() int {
	return xxx_messageInfo_ShortDetailReply.Size(m)
}
func (m *ShortDetailReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortDetailReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShortDetailReply proto.InternalMessageInfo

func (m *ShortDetailReply) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ShortDetailReply) GetShortener() string {
	if m != nil {
		return m.Shortener
	}
	return ""
}

func (m *ShortDetailReply) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

func (m *ShortDetailReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ShortDetailReply) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type QueryRequest struct {
	// url 原url
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// shortener 短链接
	Shortener string `protobuf:"bytes,2,opt,name=shortener,proto3" json:"shortener,omitempty"`
	// 页码
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// 每页显示数目
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{3}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (dst *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(dst, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *QueryRequest) GetShortener() string {
	if m != nil {
		return m.Shortener
	}
	return ""
}

func (m *QueryRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryReply struct {
	// Shortener 详情
	AppInfoList []*ShortDetailReply `protobuf:"bytes,1,rep,name=appInfoList,proto3" json:"appInfoList,omitempty"`
	// apk  总数
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryReply) Reset()         { *m = QueryReply{} }
func (m *QueryReply) String() string { return proto.CompactTextString(m) }
func (*QueryReply) ProtoMessage()    {}
func (*QueryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{4}
}
func (m *QueryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryReply.Unmarshal(m, b)
}
func (m *QueryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryReply.Marshal(b, m, deterministic)
}
func (dst *QueryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReply.Merge(dst, src)
}
func (m *QueryReply) XXX_Size() int {
	return xxx_messageInfo_QueryReply.Size(m)
}
func (m *QueryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReply proto.InternalMessageInfo

func (m *QueryReply) GetAppInfoList() []*ShortDetailReply {
	if m != nil {
		return m.AppInfoList
	}
	return nil
}

func (m *QueryReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DelEnerRequest struct {
	// url 原url
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// shortener 短链接
	Shortener            string   `protobuf:"bytes,2,opt,name=shortener,proto3" json:"shortener,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelEnerRequest) Reset()         { *m = DelEnerRequest{} }
func (m *DelEnerRequest) String() string { return proto.CompactTextString(m) }
func (*DelEnerRequest) ProtoMessage()    {}
func (*DelEnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{5}
}
func (m *DelEnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelEnerRequest.Unmarshal(m, b)
}
func (m *DelEnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelEnerRequest.Marshal(b, m, deterministic)
}
func (dst *DelEnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelEnerRequest.Merge(dst, src)
}
func (m *DelEnerRequest) XXX_Size() int {
	return xxx_messageInfo_DelEnerRequest.Size(m)
}
func (m *DelEnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelEnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelEnerRequest proto.InternalMessageInfo

func (m *DelEnerRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DelEnerRequest) GetShortener() string {
	if m != nil {
		return m.Shortener
	}
	return ""
}

type DelEnerReply struct {
	// result 删除结果
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelEnerReply) Reset()         { *m = DelEnerReply{} }
func (m *DelEnerReply) String() string { return proto.CompactTextString(m) }
func (*DelEnerReply) ProtoMessage()    {}
func (*DelEnerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_url_shortener_f26e16221dbbede9, []int{6}
}
func (m *DelEnerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelEnerReply.Unmarshal(m, b)
}
func (m *DelEnerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelEnerReply.Marshal(b, m, deterministic)
}
func (dst *DelEnerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelEnerReply.Merge(dst, src)
}
func (m *DelEnerReply) XXX_Size() int {
	return xxx_messageInfo_DelEnerReply.Size(m)
}
func (m *DelEnerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelEnerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelEnerReply proto.InternalMessageInfo

func (m *DelEnerReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "protos.GenerateRequest")
	proto.RegisterType((*GenerateReply)(nil), "protos.GenerateReply")
	proto.RegisterType((*ShortDetailReply)(nil), "protos.ShortDetailReply")
	proto.RegisterType((*QueryRequest)(nil), "protos.QueryRequest")
	proto.RegisterType((*QueryReply)(nil), "protos.QueryReply")
	proto.RegisterType((*DelEnerRequest)(nil), "protos.DelEnerRequest")
	proto.RegisterType((*DelEnerReply)(nil), "protos.DelEnerReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UrlShortEnerServiceClient is the client API for UrlShortEnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UrlShortEnerServiceClient interface {
	// 短链接生成
	ShortenerGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateReply, error)
	// 筛选查询
	ShortenerQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error)
	// 删除
	ShortenerDelete(ctx context.Context, in *DelEnerRequest, opts ...grpc.CallOption) (*DelEnerReply, error)
}

type urlShortEnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewUrlShortEnerServiceClient(cc *grpc.ClientConn) UrlShortEnerServiceClient {
	return &urlShortEnerServiceClient{cc}
}

func (c *urlShortEnerServiceClient) ShortenerGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateReply, error) {
	out := new(GenerateReply)
	err := c.cc.Invoke(ctx, "/protos.UrlShortEnerService/ShortenerGenerate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortEnerServiceClient) ShortenerQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error) {
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, "/protos.UrlShortEnerService/ShortenerQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlShortEnerServiceClient) ShortenerDelete(ctx context.Context, in *DelEnerRequest, opts ...grpc.CallOption) (*DelEnerReply, error) {
	out := new(DelEnerReply)
	err := c.cc.Invoke(ctx, "/protos.UrlShortEnerService/ShortenerDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlShortEnerServiceServer is the server API for UrlShortEnerService service.
type UrlShortEnerServiceServer interface {
	// 短链接生成
	ShortenerGenerate(context.Context, *GenerateRequest) (*GenerateReply, error)
	// 筛选查询
	ShortenerQuery(context.Context, *QueryRequest) (*QueryReply, error)
	// 删除
	ShortenerDelete(context.Context, *DelEnerRequest) (*DelEnerReply, error)
}

func RegisterUrlShortEnerServiceServer(s *grpc.Server, srv UrlShortEnerServiceServer) {
	s.RegisterService(&_UrlShortEnerService_serviceDesc, srv)
}

func _UrlShortEnerService_ShortenerGenerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortEnerServiceServer).ShortenerGenerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UrlShortEnerService/ShortenerGenerate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortEnerServiceServer).ShortenerGenerate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortEnerService_ShortenerQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortEnerServiceServer).ShortenerQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UrlShortEnerService/ShortenerQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortEnerServiceServer).ShortenerQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlShortEnerService_ShortenerDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelEnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlShortEnerServiceServer).ShortenerDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UrlShortEnerService/ShortenerDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlShortEnerServiceServer).ShortenerDelete(ctx, req.(*DelEnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UrlShortEnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UrlShortEnerService",
	HandlerType: (*UrlShortEnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShortenerGenerate",
			Handler:    _UrlShortEnerService_ShortenerGenerate_Handler,
		},
		{
			MethodName: "ShortenerQuery",
			Handler:    _UrlShortEnerService_ShortenerQuery_Handler,
		},
		{
			MethodName: "ShortenerDelete",
			Handler:    _UrlShortEnerService_ShortenerDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "url_shortener.proto",
}

func init() { proto.RegisterFile("url_shortener.proto", fileDescriptor_url_shortener_f26e16221dbbede9) }

var fileDescriptor_url_shortener_f26e16221dbbede9 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x9b, 0xcd, 0x8a, 0x9d, 0x2d, 0x6d, 0x71, 0x4b, 0x89, 0x22, 0x84, 0x2a, 0x1f, 0x50,
	0x4f, 0x3d, 0x94, 0x1b, 0xe2, 0x00, 0xa2, 0x15, 0x42, 0x82, 0x03, 0x49, 0x7b, 0x05, 0xa5, 0x61,
	0x00, 0x4b, 0x6e, 0x62, 0x1c, 0x07, 0x29, 0xfc, 0x0e, 0xfe, 0x1e, 0xff, 0x05, 0xf9, 0x23, 0x49,
	0x9b, 0x4a, 0x3d, 0xec, 0x29, 0x9e, 0xe7, 0x37, 0xef, 0x3d, 0x8f, 0x1d, 0x98, 0x54, 0x92, 0x7f,
	0x2d, 0x7f, 0x16, 0x52, 0x61, 0x8e, 0x72, 0x29, 0x64, 0xa1, 0x0a, 0x72, 0x63, 0x3e, 0x25, 0x2d,
	0x60, 0xf4, 0x5e, 0xc3, 0xa9, 0xc2, 0x18, 0x7f, 0x55, 0x58, 0x2a, 0x32, 0x85, 0x40, 0x64, 0x95,
	0xe4, 0xa1, 0x37, 0xf7, 0x16, 0xb7, 0xb1, 0x2d, 0xc8, 0x33, 0xb8, 0x3d, 0x14, 0x7b, 0xc6, 0x71,
	0x27, 0x79, 0x78, 0x65, 0x76, 0x3a, 0x80, 0x2c, 0x60, 0x64, 0x8b, 0x77, 0x9c, 0x61, 0xae, 0x34,
	0xc7, 0x37, 0x9c, 0x3e, 0x4c, 0x3f, 0xc1, 0xa3, 0xce, 0x50, 0xf0, 0x5a, 0x0b, 0xb7, 0xe1, 0x9c,
	0x65, 0x07, 0x90, 0xe7, 0x00, 0x99, 0xe9, 0xdd, 0xd6, 0x02, 0x9d, 0xef, 0x11, 0x42, 0xff, 0x7a,
	0x30, 0x4e, 0x34, 0x7b, 0x8d, 0x2a, 0x65, 0xdc, 0x4a, 0x8e, 0xc1, 0xaf, 0xd8, 0x37, 0x27, 0xa6,
	0x97, 0xa7, 0x26, 0x57, 0x97, 0x4d, 0xfc, 0xbe, 0x89, 0xd1, 0x93, 0x3c, 0xbc, 0x76, 0x7a, 0x92,
	0x9b, 0x0e, 0x89, 0xa9, 0xc2, 0x2d, 0x3b, 0x60, 0x18, 0xb8, 0x8e, 0x16, 0xa1, 0x39, 0x0c, 0x3e,
	0x57, 0x28, 0xeb, 0x66, 0xa6, 0x4e, 0xc1, 0xeb, 0x14, 0x2e, 0x27, 0x22, 0x70, 0x2d, 0xd2, 0x1f,
	0x36, 0x4b, 0x10, 0x9b, 0x35, 0x89, 0xe0, 0xa1, 0xfe, 0x26, 0xec, 0x0f, 0x9a, 0x28, 0x41, 0xdc,
	0xd6, 0xf4, 0x0b, 0x80, 0xf3, 0xd3, 0xe7, 0x7f, 0x05, 0x77, 0xa9, 0x10, 0x1f, 0xf2, 0xef, 0xc5,
	0x47, 0x56, 0xaa, 0xd0, 0x9b, 0xfb, 0x8b, 0xbb, 0x55, 0x68, 0x6f, 0xbe, 0x5c, 0xf6, 0xc7, 0x15,
	0x1f, 0x93, 0xf5, 0xed, 0x67, 0x45, 0x95, 0x2b, 0x93, 0x29, 0x88, 0x6d, 0x41, 0xdf, 0xc0, 0x70,
	0x8d, 0x7c, 0x93, 0xa3, 0xbc, 0xe7, 0x89, 0xe8, 0x0b, 0x18, 0xb4, 0x0a, 0x3a, 0xe3, 0x0c, 0x6e,
	0x24, 0x96, 0x15, 0x57, 0x4e, 0xc2, 0x55, 0xab, 0x7f, 0x1e, 0x4c, 0x76, 0x92, 0x9b, 0x90, 0x9a,
	0x9d, 0xa0, 0xfc, 0xcd, 0x32, 0x24, 0x1b, 0x78, 0x9c, 0x34, 0x62, 0xcd, 0x03, 0x22, 0x4f, 0x9b,
	0x33, 0xf5, 0xde, 0x70, 0xf4, 0xe4, 0x7c, 0x43, 0xf0, 0x9a, 0x3e, 0x20, 0xaf, 0x61, 0xd8, 0xca,
	0x98, 0x89, 0x91, 0x69, 0x43, 0x3d, 0xbe, 0xb0, 0x88, 0xf4, 0x50, 0xdb, 0xfd, 0x16, 0x46, 0x6d,
	0xf7, 0x1a, 0x39, 0x2a, 0x24, 0xb3, 0x86, 0x78, 0x3a, 0x9f, 0x68, 0x7a, 0x86, 0x1b, 0x89, 0xbd,
	0xfd, 0xf1, 0x5e, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x38, 0x27, 0x81, 0x96, 0x03, 0x00,
	0x00,
}
